[최민석] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #10
Opened 2022-04-15 07:09 UTC by alexms0316

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입기능구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이름, 이메일, 패스워드, 휴대폰번호로 회원가입 가능
- 실패시 에러 반환
- 패스워드, 이메일 정해진형식에서 벗어날 경우 에러
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-15 07:20 UTC, kyeongraekim requested changes

2022-04-15 07:20 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 400)
해당 내용을 잘 작성해주셨네요. 혹시 validation.py 파일에 따로 만들어서 해당 내용에 대한 모듈화를 진행해보시는것은 어떨까요?

2022-04-15 07:20 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 400)
정규표현식은 상수데이터 임으로 컨벤션에 맞게 변수명을 모두 대문자로 설정해주셔야 합니다.

2022-04-15 07:20 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +            phone_number = data['phone_number']
위코드 컨벤션에 맞게 가장 긴 변수명을 기준으로 한칸 스페이싱을 주어 가독성이 좋아지도록 재정렬 해주세요~

2022-04-15 07:20 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +            password_crypt = bcrypt.hashpw(password, bcrypt.gensalt()).decode('utf-8')
bcrypt는 mission3 가아닌 mission5에 해당되는 내용입니다. 위에 임포트 문과 해당내용은 삭재해주세요~

2022-04-15 07:20 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +            User.objects.create(name = name, email = email, password = password_crypt, phone_number = phone_number)
이곳도 재푸시해주실 때 위코드 컨벤션에 맞게 가독성을 높여 재정렬 해주세요~

2022-04-15 08:25 UTC, alexms0316 commented on students/minseok/westagram/users/views.py
> +            User.objects.create(name = name, email = email, password = password_crypt, phone_number = phone_number)
경래멘토님. 이부분은 한줄이 띄어쓰기가 되어있던 부분이 가독성을 헤친 것인가요??

2022-04-15 08:56 UTC, alexms0316 commented on students/minseok/westagram/users/views.py
> +            User.objects.create(name = name, email = email, password = password_crypt, phone_number = phone_number)
앗.. 멘토님 해결 완료하였습니다....ㅋㅋㅋ...

2022-04-17 04:46 UTC, kyeongraekim requested changes

2022-04-17 04:46 UTC, kyeongraekim commented on students/minseok/westagram/users/validation.py
> +          Regex_password = '\S{8,25}'
파이썬에서의 상수 데이터를 담은 변수네이밍은 어떻게 처리하는지 다시 리서치 및 확인해보세요~

2022-04-17 04:46 UTC, kyeongraekim commented on students/minseok/westagram/users/validation.py
> +          if not re.match(Regex_email, str(User.email)):
User.email로 표현된 부분과 str으로 변환하는 작업이 불필요해보이네요! 사용하실 내용 값을 parameter 및  인자값의 형태로 View 파일에서 받아올 수 있지 않을까요?

2022-04-17 04:46 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +class SignUpView(View):
가독성을 위해서 클래스 시작시 한줄의 공백을 띄어주세요~

2022-04-18 07:35 UTC, merged