[안남규] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #11
Opened 2022-04-15 08:14 UTC by NamkyuAhn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Created : users.urls, users.views.JoinView
Edited : westagram.urls
		 
## 수정 사항들 자세한 내용
check_email_validation, check_password_validation을 통해 이메일, 비밀번호가 조건에 맞는지 확인, 통과 못할시 validation error message와 함께 status 400 반환

users 테이블에 이미 존재하는 email로 회원가입할려면 email already exists 메세지와 함께 status 400 반환

email이나 password가 빈값으로 주어진 경우 key error message와 함께 status 400 반환

위와 같은 일련의 과정 전부 통과시 정상적으로 users 테이블에 주어진 데이터 삽입함

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-17 04:52 UTC, kyeongraekim requested changes

2022-04-17 04:52 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +        return False
작성해주신 코드의 re.match 의 반환값이 각각의 경우의 수에서 어떻게 나오나요? 해당 내용처럼 if-else로의 추가 분기가 꼭 필요한 사항일까요? 한 번 재고해주세요!~

2022-04-17 04:52 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +class JoinView(View):
회원가입 클래스 임으로 Join이라는 영문 명칭은 조금 부족해보일 수 있어 보이네요!~ Register나 SignUp 정도로 수정해보는 것은 어떨까요?

2022-04-17 04:52 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +            return JsonResponse({'MESSAGE' : 'Email already Exists'},status=400)
- 불필요하게 if-elif로의 조건절 chaining으로 느껴지네요. 위의 로직을 구사하는데 있어서 꼭 if-elif로의 분기가 필요할까요?

2022-04-17 04:52 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +        data_keys = list(data.keys())
data_keys에 담긴 내용을 보다 명확하게 확인할 수 있게 변수에서 풀어서 써보세요~ 아래와같이 풀어 내어서 try-except 문을 사용한 후, 장고에서 제공하는 key_error 핸들링을 사용하면 코드 가독성과, 디버깅은 물론 각각에 키로 들어가는 내용을 코드에서 명시할 수 있어서 좋을 것 같네요!~
```python
email = data[email]
password = data[password]

2022-04-18 05:08 UTC, kyeongraekim requested changes

2022-04-18 05:08 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +reg_password = r'^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
정규표현식을 표현할 때 통상적으로 사용하는 원어인 REGEX 를 변수명에 넣어주세요.
그리고 상수데이터를 담는 변수명 네이밍은 대문자로 이루어져야 합니다.

2022-04-18 05:08 UTC, kyeongraekim commented on students/namkyu/users/urls.py
> +    path('/join', RegisterView.as_view())
url endpoint 도 클래스명과 유사하게 진행해주시면 좋을 것 같네요, /register 정도로 수정해주세요~

2022-04-18 05:21 UTC, NamkyuAhn commented on students/namkyu/users/urls.py
> +    path('/join', RegisterView.as_view())
위 두개 부분 수정 완료하였습니다~

2022-04-18 07:30 UTC, kyeongraekim requested changes

2022-04-18 07:30 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +        e = list(User.objects.filter(name='user9').values())
해당 부분은 하드코딩 되어서 작성된 부분으로 실제 상용화되는  코드에서는 사용을 지양해주셔야 합니다.
user9이라는 이름의 유저만 이곳에서 명시할 필요가 없어 보입니다~ 하드코딩 부분을 삭제해주시고 아래 이어지는 코드도 그에 맞게 수정해주세요~

2022-04-18 07:30 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +                phone_number=data['phone_number'],
해당 내용 컨벤션에 맞게 재정렬 하여서 푸시해주세요~ 가장 긴 변수명을 기준으로 한칸 띄우시면 됩니다.

2022-04-18 07:30 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +        try :
try를 이곳에 선언하시면 위 22번 쨰 라인에서 일어날 수 있는 키에러는 핸들링을 못하게 됩니다. 올바른 위치로 옮겨주세요~

2022-04-18 08:33 UTC, NamkyuAhn commented on students/namkyu/users/views.py
> +        e = list(User.objects.filter(name='user9').values())
해당 부분은 제가 테스트를 하다가 실수로 안지우고 올린것 같습니다. 지운버전으로 다시 올렸습니다~

2022-04-18 08:33 UTC, NamkyuAhn commented on students/namkyu/users/views.py
> +        try :
요청하신부분 모두 수정하여 커밋했습니다~

2022-04-18 08:48 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-18 08:48 UTC, merged

2022-04-18 08:49 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +        e = list(User.objects.filter(name='user9').values())
넵 실무나가서 하드코딩 된 버젼을 절대 올려서는 안되기에 이곳에서 다시 한 번 강조드립니다! 참고 해주세요~ ㅎㅎ