Feature/youngbin signup
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #12
Opened 2022-04-15 09:01 UTC by tbhumblestar

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-17 04:58 UTC, kyeongraekim requested changes

2022-04-17 04:58 UTC, kyeongraekim commented on students/youngbin/users/validation.py
> +        return password
이메일에서 잘 작성해주신 것 처럼 위 비밀번호의 정규표현식을 하나의 긴 정규표현식으로 바꾸어보세요~ 클라이언트와 소통하며 리턴 하는 메세지는 비밀번호 validation 통과 여부만을 invalid_password 정도로만 안내해주어도 좋습니다. 오히려 해당 계정을 탈취하려는 시도에서 큰 힌트를 줄 수 있는 세부 내용 제공은 지양해주세요

2022-04-17 04:58 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +        #KeyError check
코드 독해로 충분히 확인가능한 불필요한 코드 주석은 삭제해주세요~

2022-04-17 04:58 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +                return JsonResponse({"message":"ALREADY_EXISTED_EMAIL"},status=409)
- 이메일의 중복 가입 여부를 확인하기 위해서 작성하신듯한 본 코드 내용은 너무 불필요한 연산이 많이 들어갑니다. 유저가 50만명이라고 가정한다면 50만개의 유저 데이터를 db에서 파이썬 단으로 끌고들어와서 리스트 메소드를 작업한다는 뜻인데 너무 비효율적으로 보입니다. 
- 대신에 장고에서 제공하는 .exists() 쿼리셋 api 메소드를 통해서 중복 여부를 검증해주세요~

2022-04-18 04:53 UTC, tbhumblestar commented
password validation을 위한 정규표현식을  한 줄로 만들긴 했는데 정확한 이해가 가지 않습니다(테스트 결과 의도한대로 작동하기는 합니다.) 혹시 대략적으로 설명해주실 수 있으실까요? 찾아봐도 이렇게 써라라는 내용만 있고 그의미를 말해주는 곳이 잘 보이지 않더라구요 ㅠㅠ 다른건 어느정도 이해하겠는데  (?=.*) 이부분의 의미와 원리를 잘 모르겠습니다.
REGEX_PASSWORD = '^(?=.*[\d])(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*()])[\w\d!@#$%^&*()]{8,}$'

2022-04-18 05:02 UTC, kyeongraekim requested changes

2022-04-18 05:02 UTC, kyeongraekim commented on students/youngbin/users/validation.py
> +        return JsonResponse({"message":"Incorrect password format"},status=401)
8번라인의 401과 14번 라인의 400 상태코드가 같은 상황에서의 리턴 상태코드가 서로 다르네요! 
둘 중 더 올바른 것으로 선택하여 통일 시켜주세요~

2022-04-18 05:02 UTC, kyeongraekim commented on students/youngbin/users/validation.py
> +    return phone_number
```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(value) :    
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')

def validate_password(value) :
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_PASSWORD')

2022-04-18 05:02 UTC, kyeongraekim commented on students/youngbin/users/validation.py
> +    return phone_number
리턴 말고 raise로 에러를 강제로 일으키는 방법도 있습니다. validation.py를 위와 같이 변경해주시고, View.py 에서는 아래와 같이 진행해보심을 추천드립니다~

```python
except ValidationError as error:
    JsonResponse({"message": error.message}, status=409)

2022-04-18 05:47 UTC, tbhumblestar commented on students/youngbin/users/validation.py
> +    return phone_number
views.py의 내용에 return JsonResponse를 해주지 않아도 괜찮은가요?

2022-04-18 07:21 UTC, kyeongraekim commented
> password validation을 위한 정규표현식을 한 줄로 만들긴 했는데 정확한 이해가 가지 않습니다(테스트 결과 의도한대로 작동하기는 합니다.) 혹시 대략적으로 설명해주실 수 있으실까요? 찾아봐도 이렇게 써라라는 내용만 있고 그의미를 말해주는 곳이 잘 보이지 않더라구요 ㅠㅠ 다른건 어느정도 이해하겠는데 (?=._) 이부분의 의미와 원리를 잘 모르겠습니다. REGEX_PASSWORD = '^(?=._[\d])(?=._[A-Z])(?=._[a-z])(?=._[!@#$%^&_()])[\w\d!@#$%^&*()]{8,}$'

아래 내용을 한 번 참고해보세요!~ 정규표현식은 일종의 규칙을 그대로 따르기만 하면 되는 부분이라서 어렵게 생각하실 필요 없습니다!~
https://myeonguni.tistory.com/1555

2022-04-18 07:26 UTC, kyeongraekim requested changes

2022-04-18 07:26 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +class UserView(View):
회원가입 View임을 명시할 수 있도록 SignUpView 정도로 수정해주세요~

2022-04-18 07:26 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +        return JsonResponse({'messasge':'created'}, status=201)
try-except 문을 위와 같이 여러개로 나누어서 사용 하지마시고 아래와 같이 전체 코드 흐름에 대한 시도, 그에 대한 가능성 있는 에러 핸들링의 관점으로 접근해주세요~

```python

        try:
            new_email        = data['email']
            new_password     = data['password']
            new_name         = data['name']
            new_phone_number = data['phone_number']


        try:
            validated_pw = validate_password(new_password)
            validated_email = validate_email(new_email)
            validated_phone_number = validate_phone_number(new_phone_number)

        if User.objects.filter(email=new_email).exists():
            return JsonResponse({"message":"ALREADY_EXISTED_EMAIL"},status=409)

        User.objects.create(
            name         = new_name,
            password     = validated_pw,
            email        = validated_email,
            phone_number = validated_phone_number,
        )
        return JsonResponse({'messasge':'created'}, status=201)

except KeyError:
            return JsonResponse({"message":"KEY_ERROR"},status=400)
except ValidationError as error:
            return JsonResponse({"message": error.messages}, status=409)

2022-04-18 07:37 UTC, kyeongraekim requested changes

2022-04-18 07:37 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +class UserView(View):
아직 클래스 명은 수정이 안되어있네요!~

2022-04-18 07:37 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +            validated_phone_number = validate_phone_number(new_phone_number)
이곳도 정렬 한번만 신경써주시고~ 웹 개발 코든에서는 축약어를 최대한 지양해서 사용해주세요~
제 3자의 가독성을 위해서 password로 풀어서 수정해주세요~

2022-04-18 08:08 UTC, kyeongraekim requested changes

2022-04-18 08:08 UTC, kyeongraekim commented on students/youngbin/users/urls.py
> +    path('/signup',views.UserView.as_view())
SignUpView로 명칭을 바꿨다면 해당 내용도 동일하게 바꿔주셔야 할 것 같네요!~ 런서버 및 통신 시험을 꼭 해보고 깃헙에 올리는 것을 습관화해주세요!~

2022-04-18 08:47 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-18 08:47 UTC, merged