Add : login feature
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #15
Opened 2022-04-18 11:20 UTC by NamkyuAhn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Add : 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
키 에러가 발생할 경우, KEY_ERROR 메시지와 함께 400 에러를 반환합니다.

사용자가 입력한 이메일이 db에 존재하지 않을경우, EMAIL NOT EXIST 메시지와 함께 401 에러를 반환합니다.

이메일이 일치하면 해당 이메일을 사용하는 유저의 비밀번호를 변수로 저장해 이를 입력한 비밀번호와 비교합니다. 만약 비밀번호가 일치하지 않을 경우, PASSWORD ERROR 메시지와 함께 401 에러를 반환합니다.

상기의 과정을 전부 통과할 시 LOGIN SUCCESS 메시지와 함께 200을 반환합니다.

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-18 18:24 UTC, tbhumblestar commented on students/namkyu/users/views.py
> +                real_password = User.objects.get(email=data['email']).password
filter에 조건을 함꼐 주는 건 어떨까요?
filter(email=email,password=password).exists():
와 같은 방법으로요

2022-04-18 18:28 UTC, tbhumblestar commented on students/namkyu/users/views.py
> +                return JsonResponse({'MESSAGE' : 'LOGIN SUCCESS'}, status = 200)
filter에 조건을 함꼐 주는 건 어떨까요?  ','를 사용해서 and조건을 붙일 수 있다고 하네요
ex) filter(email=email,password=password).exists():

+추가로, 과제에서는 이메일이나 패스워드가 유효하지 않으면 동일하게 INVALID_USER를 반환하라고 하더라구요
로그인이 실패했을 경우 제공되는 정보를 최소화 시키켜서 보안을 높이려는 의도같습니다

2022-04-19 01:17 UTC, alexms0316 commented on students/namkyu/users/views.py
> +
보안문제와 관련하여 get, post 어느 것을 사용하는지 관련해서 다시 한번 고려해주세요!
([https://velog.io/@jch9537/REST-API-LogIn-GET-vs-POST참고](https://velog.io/@jch9537/REST-API-LogIn-GET-vs-POST%EC%B0%B8%EA%B3%A0))

2022-04-19 01:21 UTC, NamkyuAhn commented on students/namkyu/users/views.py
> +                return JsonResponse({'MESSAGE' : 'LOGIN SUCCESS'}, status = 200)
filter부분 말씀드린대로 수정했습니다

2022-04-19 01:21 UTC, NamkyuAhn commented on students/namkyu/users/views.py
> +
링크가 404가 뜨네요 ㅠㅠ 다른글 보고 get에서 post로 바꿨습니다

2022-04-19 01:36 UTC, alexms0316 commented on students/namkyu/users/views.py
> +
LGTM!!

2022-04-19 05:11 UTC, kyeongraekim requested changes

2022-04-19 05:11 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +            if not User.objects.filter(email=data['email'], password=data['password']).exists():
추후 코드의 확장성을 위해서 email 과 password를 각각의 별도 변수에 담아서 재사용성을 높여주면 좋을 것 같네요~

2022-04-19 05:11 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +            else:
이곳도 논리구조상 else로의 추가 분기 없이 진행하면 어떨까요?

2022-04-19 06:01 UTC, NamkyuAhn commented on students/namkyu/users/views.py
> +            else:
말씀드린 부분들 수정하였습니다~

2022-04-19 06:05 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-19 06:05 UTC, merged