signin finsihed 0.1
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #16
Opened 2022-04-18 11:50 UTC by tbhumblestar

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-18 18:19 UTC, tbhumblestar commented on students/youngbin/users/views.py
> +            password = data['password']
asd

2022-04-19 01:21 UTC, alexms0316 commented on students/youngbin/users/views.py
> +            return JsonResponse({"message":"KEY_ERROR"},status=400)
열심히 찾았는데.. 완벽한 코드인 것 같습니다 LGTM!!

2022-04-19 01:22 UTC, NamkyuAhn commented
LGTM~

2022-04-19 01:34 UTC, imsooyeon commented
LGTM^^

2022-04-19 05:09 UTC, kyeongraekim requested changes

2022-04-19 05:09 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +class SigninView(View):
이곳 클래스명도 SignUpView와 같이 중간 i에 해당되는 내용의 포맷을 일치시키면 좋을 것 같습니다~

2022-04-19 05:09 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +            else:
그리고 이곳에 else로의 추가 분기 없이 바로 원하는 내용을 리턴하게 하면 어떨까요?

2022-04-19 06:18 UTC, kyeongraekim requested changes

2022-04-19 06:18 UTC, kyeongraekim commented on students/youngbin/users/urls.py
> +    path('/signin',views.SigninView.as_view()),
url 부분은 수정이 덜되어있네요? 꼭 코드 수정 이후에는 런서버 이후 통신 시험까지 해보는 것을 습관화해주세요!~

2022-04-19 06:19 UTC, kyeongraekim requested changes

2022-04-19 06:19 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +            if User.objects.filter(email=email,password=password).exists():
가독성을 위해 if 시작 부분을 한 줄 띄어주시면 좋을 것 같습니다

2022-04-19 06:19 UTC, kyeongraekim commented on students/youngbin/users/views.py
> +            return JsonResponse({"message":"INVALID_USER."},status=401)
가독성을 위해 또다른 return 시작 부분을 한 줄 띄어주시면 좋을 것 같습니다

2022-04-19 06:26 UTC, tbhumblestar commented on students/youngbin/users/views.py
> +            return JsonResponse({"message":"INVALID_USER."},status=401)
확인했습니다!

2022-04-19 07:38 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-19 07:38 UTC, merged