[임수연] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #18
Opened 2022-04-18 15:15 UTC by imsooyeon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 view 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 view 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-18 18:20 UTC, tbhumblestar commented on students/sooyeon/users/views.py
>  from xml.dom import ValidationErr
신원이 불분명한 친구네요!

2022-04-18 18:20 UTC, tbhumblestar commented on students/sooyeon/users/views.py
> +            password = data['password']
정렬하면 더 좋을 것 같습니다!

2022-04-18 18:21 UTC, tbhumblestar commented on students/sooyeon/users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 200)
email이 유효할 때, 해당 email의 password와 일치하지 않아도 password가 db내에 존재하기만 한다면 200 success를 보내는 것 같습니다!

2022-04-19 01:23 UTC, NamkyuAhn commented on students/sooyeon/users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 200)
저도 영빈님과 같은 의견입니다

2022-04-19 01:23 UTC, alexms0316 commented on students/sooyeon/users/views.py
> +            if not User.objects.filter(email = email).exists():
애러 메세지가 동일하니 이메일과 패스워드를 합쳐서 코드를 줄이는 방법도 좋은 것 같습니다

2022-04-19 01:36 UTC, imsooyeon commented on students/sooyeon/users/views.py
> +            password = data['password']
수정했습니다!

2022-04-19 01:36 UTC, imsooyeon commented on students/sooyeon/users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 200)
수정했습니다!

2022-04-19 01:37 UTC, imsooyeon commented on students/sooyeon/users/views.py
> +            if not User.objects.filter(email = email).exists():
수정했습니다!!

2022-04-19 01:43 UTC, alexms0316 commented on students/sooyeon/users/views.py
> +            if not User.objects.filter(email = email).exists():
AFAIK(As Far As I Know).. LGTM!

2022-04-19 02:07 UTC, imsooyeon commented on students/sooyeon/users/views.py
>  from xml.dom import ValidationErr
수정했습니다

2022-04-19 02:39 UTC, NamkyuAhn commented
lgtm~

2022-04-19 05:07 UTC, kyeongraekim requested changes

2022-04-19 05:07 UTC, kyeongraekim commented on students/sooyeon/users/views.py
> +            else:
이곳에 else를 안쓰고 진행해도 논리 연계상 문제 없고 깔끔해 보일 것 같네요!~

2022-04-19 06:13 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-19 06:13 UTC, merged