[안남규] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #19
Opened 2022-04-19 06:26 UTC by NamkyuAhn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- bcrypt 사용하여 비밀번호를 db에 저장할때 암호화된 해시값이 저장되게 구현
		 
## 수정 사항들 자세한 내용
- 회원가입 과정의 오류및 validation 검출 조건들을 통과하면 bcrypt를 사용해 사용자가 입력한 비밀번호를 db에 암호화된 해시값으로 저장합니다

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-19 07:16 UTC, tbhumblestar commented on students/namkyu/users/views.py
> +
정렬해주시면 더 좋을 것 같습니다~

2022-04-19 07:17 UTC, tbhumblestar commented on students/namkyu/users/views.py
>                  phone_number = data['phone_number'],
이것도 = 위치 맞춰서 정렬해주시면 좋을 것 같습니다~

2022-04-19 07:20 UTC, NamkyuAhn commented on students/namkyu/users/views.py
>                  phone_number = data['phone_number'],
수정했습니다~

2022-04-19 07:43 UTC, alexms0316 commented
LGTM!

2022-04-20 01:25 UTC, kyeongraekim requested changes

2022-04-20 01:25 UTC, kyeongraekim commented on students/namkyu/users/views.py
> +                password     = hashed_password,
email, password 등의 내용은 20번째 라인부터 1회 이상 사용되는 데이터로 보여지는데 재사용성 향상을 위해서 변수에 담아서 코드를 진행해보세요~

2022-04-20 01:34 UTC, NamkyuAhn commented on students/namkyu/users/views.py
> +                password     = hashed_password,
수정하였습니다~

2022-04-20 02:28 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-20 02:28 UTC, merged