[최민석] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/32-westagram-backend-3-team pull request #21
Opened 2022-04-19 07:41 UTC by alexms0316

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-19 07:58 UTC, imsooyeon commented on students/minseok/westagram/users/views.py
>                    phone_number = phone_number
코드 정렬하면 더 깔끔할 것 같아요!

2022-04-19 07:59 UTC, NamkyuAhn commented on students/minseok/westagram/users/views.py
> +              password_bcrypt = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
password field를 models에서 정의했을때 binary가 아닌 charfield로 선언했기 때문에 지금 바이트타입 그대로 db에 넣으면 오류가 날 수도 있습니다. decode를 추가해 주세요~

2022-04-19 08:04 UTC, alexms0316 commented on students/minseok/westagram/users/views.py
> +              password_bcrypt = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
완료하였습니다!

2022-04-19 08:04 UTC, alexms0316 commented on students/minseok/westagram/users/views.py
>                    phone_number = phone_number
완료하였습니다!

2022-04-19 08:09 UTC, tbhumblestar commented on students/minseok/westagram/users/views.py
> +              password_bcrypt = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
이 부분 궁금해서 한번 확인해봤는데요 저장이 되긴 하는데, 'byte'를 나타내는 b' 가 붙네요 decode하는게 확실히 좋은 것 같습니다!

2022-04-19 08:10 UTC, NamkyuAhn commented on students/minseok/westagram/users/views.py
> +              password_bcrypt = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
lgtm~

2022-04-19 08:11 UTC, imsooyeon commented on students/minseok/westagram/users/views.py
>                    phone_number = phone_number
lgtm~

2022-04-20 01:21 UTC, kyeongraekim requested changes

2022-04-20 01:21 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +              password_bcrypt = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
정확히 어떠한 패키지를 썼는지를 명시하는 변수명은 좋지 않아 보입니다. hashed_password  정도의 변수명으로 수정해주세요~

2022-04-20 01:30 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-20 01:30 UTC, merged